### ISSUE TITLE
making backup doesnt support all linux config paths

### ISSUE THREAD

**Issue by aigic8** [rajasegar/alacritty-themes#172]
### Descibe the bug
If alacritty config file is not `$HOME/.config/alacritty/alacritty.yml`, (in my case it is `$HOME/.alacritty.yml`) it will throw an error

### Steps to reproduce
1. Installation:
   - installed using `npm i -g alacritty-themes`
1. Running:
   - just ran `alacritty-themes`
 
### Expected Behavior
Running normally, without errors

### Operating System 
Arch Linux (Manjaro)

### Screenshots
![alac-bug](https://user-images.githubusercontent.com/61603233/182450979-953d867c-c80c-4de2-83d6-7069eaf721c6.png)

I've looked around the source code a bit. Looks like the problem is from [createBackup](https://github.com/rajasegar/alacritty-themes/blob/master/src/helpers/index.js#L12-L27) function. On Linux, when it checks if the config exist, it will check both `$HOME/.config/alacritty/alacritty.yml` and `$HOME/.alacritty.yml`. But when it creates a backup file it will always use `$HOME/.config/alacritty/alacritty.yml`

**Comment by JuanVqz** [comment]
good call! I assumed the `alacritty.yml` file is located at `$HOME/.config/alacritty/alacritty.yml`, now I don't like the idea of creating backups in the $HOME directory. :thinking: 

The solution may be use this function https://github.com/rajasegar/alacritty-themes/blob/4519540b7b465b85272adb539a9762e2a12fcfdb/src/helpers/index.js#L85 instead of https://github.com/rajasegar/alacritty-themes/blob/4519540b7b465b85272adb539a9762e2a12fcfdb/src/helpers/index.js#L61

do you want to fix it?

**Comment by aigic8** [comment]
Thanks! But as you said, creating backup files in home direcotry is not really a neat solution. I think fixing this bug needs an oponionated solution which is beyond me.😀

**Comment by JuanVqz** [comment]
a quick and good solution could be, even if the `alacritty.yml` file is in the $HOME directory we will create the backups files in this path `$HOME/.config/alacritty/`

**Comment by JuanVqz** [comment]
I just fixed the alacritty path, please download the latest version of alacritty-themes to get it working on your end :+1: 

Thanks for reporting it
