### ISSUE TITLE
How to find out what is the current theme?

### ISSUE THREAD

**Issue by fedorpashin** [rajasegar/alacritty-themes#25]
I want to switch the theme but I don't remember which is the current one to revert it later.

If there is no such feature, the name could be written as a comment in `alacritty.yml`.

**Comment by PolSust** [comment]
Is this still an issue? I've looked into it and it seems like we could just add a `--current` flag that logs the output of `colors.name` in the alacritty config file.

#### The problem is that some themes don't have it. 
So I would just replace it with the file name. That way it would be the same that gets displayed on the list when choosing a theme,
I think that makes more sense

**Comment by JuanVqz** [comment]
Yes, still an issue.
yes, we can add that `--current` flag, we are open to PRs, thank you! :+1:
